### ISSUE TITLE
Demonstration map broken

### ISSUE THREAD

**Issue by Trial-In-Error** [NelsonMinar/vector-river-map#10]
CORS issues! - it looks like whatever web proxy / load balancer you're using isn't configured to forward traffic correctly. Since somebits.com:8080/ is requesting from somebits.com/8001/ without using a CORS handshake, none of the map data is loaded, and many (many) javascript errors are generated.

**Comment by NelsonMinar** [comment]
Thanks for the report! Could you try it again? The demo server I was running had crashed, I just restarted it. If it still doesn't work could you give me a URL that is not working for you?

This demo is working fine right now: http://www.somebits.com/rivers/rivers-d3leaflet.html#8/37.959/-120.976

**Comment by Trial-In-Error** [comment]
Seems to be working just fine now! Thanks! =)
